### ISSUE TITLE
Pointer capturing doesn't work

### ISSUE THREAD

**Issue by saschanaz** [ryanburns23/img-pan-zoom#4]
In the [demo](https://www.webcomponents.org/element/ryanburns23/img-pan-zoom/demo/demo/index.html):

1. Zoom in
2. Drag from inside of image to outside of browser window
3. Release mouse button and return to inside of image

Expected result: Nothing should happen on the step 3

Actual result: Panning occurs

**Comment by ryanburns23** [comment]
@SaschaNaz  
Try this: https://user-content-dot-custom-elements.appspot.com/ryanburns23/img-pan-zoom/v1.1.0/img-pan-zoom/demo/index.html

That is what the iframe loads on wc.org, seems to work fine when not in a modal.

**Comment by saschanaz** [comment]
Yes it works on the page. Not sure why the thing is broken on iframe.
